name: CubWorlds
version: ${version}
main: io.github.devbd1.CubWorlds.Main
api-version: '1.21'
description: Lightweight custom world manager with void world support and grief prevention.
authors: [ DevBD1 ]
website: https://labs.cublex.net
load: POSTWORLD
softdepend:
  - Cub
  - CubDialogs
commands:
  CubWorlds:
    description: Manage the custom worlds
    usage: /CubWorlds <subcommand>
    aliases: [cw]
permissions: {}
