name: KuksoWorlds
main: com.kukso.mc.worlds.Main
version: ${version}
api-version: '1.21'
load: POSTWORLD
authors: [ DevBD1 ]
description: Lightweight custom world manager with essential features.
website: https://labs.cublex.net
depend:
  - KuksoLib
softdepend:
  - PlaceholderAPI
# You can manage each subcommand in config.yml
commands:
  kuksoworlds:
    usage: /kuksoworlds <subcommand>
    permission: kuksoworlds.command.root
    description: KuksoWorlds main command
    aliases: [kw]
# Permissions are dynamically set for each command in config.yml
permissions:
  kuksoworlds.admin:
    description: Allows high-level admin access to any command
    default: op
  kuksoworlds.mod:
    description: Allows low-level access to some admin commands
  kuksoworlds.user:
    description: Allows access to user commands
  kuksoworlds.command.root:
    description: Use it with specific perm(s) of a subcommand